DROP TABLE IF EXISTS INSTITUTION CASCADE;

DROP TABLE IF EXISTS LOCATION CASCADE;

DROP TABLE IF EXISTS PERSON CASCADE;

DROP TABLE IF EXISTS TERRITORY CASCADE;

DROP TABLE IF EXISTS ZNORESULT CASCADE;